### ISSUE TITLE
Заменить свг

### ISSUE THREAD

**Issue by ademaro** [jokerinteractive/direct-all-in#11]
надо заменить, тк это png в base64  в svg контейнере...

```
img/adwors-configuration-sprt.svg
img/browser-direct-logo.svg
img/browser-sprt.svg
img/calmness/promises-left-brace.svg
img/faq-bg.svg
img/header-dashed-line.svg
img/icons/icon_adwords-small.svg
img/icons/icon_book.svg
img/icons/icon_cursor.svg
img/icons/icon_mobile-phone.svg
img/icons/icon_report.svg
img/no-magic/no-magic-bg.svg
img/portfolio/clinets-bg.svg
img/portfolio/oren-house.svg
img/puzzles/puzzle-analyst.svg
img/puzzles/puzzle-directolog.svg
img/puzzles/puzzle-manager.svg
img/puzzles/puzzle-operator.svg
img/puzzles/puzzle-top-bg-light.svg
img/puzzles/puzzle-top-bg.svg
img/services-list/adwords.svg
img/services-list/complex.svg
img/services-list/direct.svg
img/services-list/maintenance.svg
img/services-list/training.svg
img/vedenie-browser-sprt.svg
img/will-never-collaborate/humor-words-bg.svg
img/will-never-collaborate/top-arrow-bg.svg
img/will-never-collaborate/will-never-collaborate-sprt.svg
img/work-stages/stage-round-sprt.svg
img/work-stages/stage-round.svg
img/yandex-direct-logo.svg
```

**Comment by ademaro** [comment]
решено нет? На кого поставить?

**Comment by DoYouLikeOrigami** [comment]
Это Алексея svg все. Видимо, он их как-то обработал и формат изменился

**Comment by AlekseyTrubitsyn** [comment]
Да, все мои. Photoshop как-то странно экспортировал svg... Влад вроде обещал подготовить, спрошу сегодня его еще раз.

**Comment by DoYouLikeOrigami** [comment]
Алексей, смотри через браузер (просто кидаешь в окно) или svg программку, что там изображено, переименовываешь, как нужно и закидываешь)

P.S. У нас с тобой некоторые пересекаются, например, в папке icons icon_book и моя book =)
Можешь просто некоторые на мои перенаправить, чтобы не плодить)

**Comment by AlekseyTrubitsyn** [comment]
Да, это понятно) Для меня было неочевидно, что мы делаем все без спрайтов. Сейчас все буду менять

**Comment by AlekseyTrubitsyn** [comment]
Готово!

**Comment by ademaro** [comment]
img/services-list/maintenance.png и img/services-list/training.png есть в свгшках, же! зачем пнг? da99f53
