### ISSUE TITLE
Услуги

### ISSUE THREAD

**Issue by ademaro** [jokerinteractive/direct-all-in#12]
- [x] вертикальное выравнивание и немного по сетке https://yadi.sk/i/XzcsztBjrS2qq https://yadi.sk/i/waZ5fJSOrS2yA
- [x] https://yadi.sk/i/q0ZgAAwhrnf8z
- [x] https://yadi.sk/i/IvEONIXJrnfCu не тот отступ
- [x] https://yadi.sk/i/IvEONIXJrnfCu отступы блоков. Неужели при пп не видно было столько косяков?)
- [x] отступ и ширина контролов https://yadi.sk/i/CERQvOltrnfQQ см.#24

**Comment by DoYouLikeOrigami** [comment]
по pixel perfect подогнать, иначе говоря?)

**Comment by ademaro** [comment]
ну да, тк расхождения сильные очень

**Comment by AlekseyTrubitsyn** [comment]
Сегодня сделаю
