### ISSUE TITLE
Вебинар

### ISSUE THREAD

**Issue by ademaro** [jokerinteractive/direct-all-in#14]
- [x] те же проблемы с минимальной шириной
- [x] что с валидацией? Откуда, например, тег `wrapper`? Ну и с именами классов я бы порефакторил, но ладно, не оплачивают это(
- [x] цвет для bg фонов добавить так же
- [x] pixel perfect небольшой бы, а то жестим https://yadi.sk/i/g-eUQEKnrS5XZ
- [x] чёт с размерами и тут: https://yadi.sk/i/9LjMIGObrS5ac
- [x] https://yadi.sk/i/qcw1MFoorngir отступ пропустили

**Comment by DoYouLikeOrigami** [comment]
А что с тегом wrapper не так? 
"Православный" тег-обёртка))

**Comment by ademaro** [comment]
Найди мне в спеке тег `wrapper` и оставим)

**Comment by DoYouLikeOrigami** [comment]
А что такое спек?)

**Comment by ademaro** [comment]
Спецификация. У html их две: [спецификация для разработчиков от WHATWG](https://developers.whatwg.org/) ([в другом виде](https://html.spec.whatwg.org/multipage/)), [последняя спецификация от консорциума W3C](https://www.w3.org/TR/html51/)

**Comment by DoYouLikeOrigami** [comment]
И он туда не включен? Странно, а зачем его ввели тогда?.. По-моему, удобно

**Comment by DoYouLikeOrigami** [comment]
Готово
