### ISSUE TITLE
Деплой на gh-pages

### ISSUE THREAD

**Issue by ademaro** [jokerinteractive/direct-all-in#16]
Сделать более удобный деплой статики на просмотр

**Comment by DoYouLikeOrigami** [comment]
А можно поподробнее?)

**Comment by ademaro** [comment]
есть таска `gulp deploy`, можно выполнять её из текущей ветки, всё само должно выливаться в `gh-pages`, надо потестить

**Comment by ademaro** [comment]
закрываю
