### ISSUE TITLE
Добавим сортировку csscomb?

### ISSUE THREAD

**Issue by ademaro** [jokerinteractive/direct-all-in#6]
Что скажете?

**Comment by DoYouLikeOrigami** [comment]
Не знаю, что это)

**Comment by ademaro** [comment]
[вот что](https://habrahabr.ru/post/230589/)

**Comment by ademaro** [comment]
кодстайл можно сразу при написании кода соблюдать)

**Comment by DoYouLikeOrigami** [comment]
Изучу и буду внедрять по мере осознания)
